version: '3.4'

services:
  custommer-management-backend:
    image: backendcontainer
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: postgres:14.10-alpine3.18
    container_name: "sqlserver"
    hostname: "sqlserver"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: